# Generated by Django 2.0.6 on 2018-07-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180708_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': ' 用户信息', 'verbose_name_plural': ' 用户信息'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='/users/default.png', upload_to='users/%Y/%m', verbose_name='头像'),
        ),
    ]
