# Generated by Django 2.0.6 on 2018-07-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180717_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='/users/teacher/default.png', upload_to='users/teachers/%Y/%m', verbose_name='负责人照片'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='edu_bak',
            field=models.CharField(choices=[('未填', '未填'), ('大一', '大一'), ('大二', '大二'), ('大三', '大三'), ('大四', '大四'), ('大五', '大五'), ('研一', '研一'), ('研二', '研二'), ('研三', '研三')], default=0, max_length=50, verbose_name='当前学历'),
        ),
    ]
