# Generated by Django 2.0.6 on 2018-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180718_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('z', '未填'), ('a', '安全科学与工程学院'), ('b', '环境科学与工程学院'), ('c', '材料科学与工程学院'), ('d', '化工学院'), ('e', '化学与分子工程学院'), ('f', '电气工程与控制科学学院'), ('g', '机械与动力工程学院'), ('h', '能源科学与工程学院'), ('i', '药学院'), ('j', '建筑学院'), ('k', '艺术设计学院'), ('l', '经济与管理学院'), ('m', '法学院'), ('n', '马克思主义学院'), ('o', '外国语言文学学院'), ('p', '体育部'), ('q', '生物与制药工程学院'), ('r', '食品与轻工学院'), ('s', '计算机科学与技术学院'), ('t', '数理科学学院'), ('u', '测绘科学与技术学院'), ('v', '城市建设学院'), ('w', '交通运输工程学院'), ('x', '土木工程学院')], default='z', max_length=20, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='edu_bak',
            field=models.CharField(choices=[('未填', '未填'), ('大一', '大一'), ('大二', '大二'), ('大三', '大三'), ('大四', '大四'), ('大五', '大五'), ('研一', '研一'), ('研二', '研二'), ('研三', '研三')], default='未填', max_length=50, verbose_name='当前学历'),
        ),
    ]
