# Generated by Django 2.0.6 on 2018-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180718_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(choices=[('wt', '未填'), ('bj', '北京'), ('tj', '天津'), ('sh', '上海'), ('cq', '重庆'), ('hb', '河北'), ('sx', '山西'), ('ln', '辽宁'), ('jl', '吉林'), ('hlj', '黑龙江'), ('js', '江苏'), ('zj', '浙江'), ('ah', '安徽'), ('fj', '福建'), ('jx', '江西'), ('sd', '山东'), ('hn', '河南'), ('hb', '湖北'), ('hn', '湖南'), ('gd', '广东'), ('hn', '海南'), ('sc', '四川'), ('gz', '贵州'), ('yn', '云南'), ('sx', '陕西'), ('gs', '甘肃'), ('qh', '青海'), ('tw', '台湾'), ('nmg', '内蒙古'), ('gx', '广西'), ('xz', '西藏'), ('nx', '宁夏'), ('xj', '新疆'), ('xg', '香港'), ('am', '澳门')], default='wt', max_length=5, verbose_name='省份'),
        ),
    ]
