# Generated by Django 2.0.6 on 2018-07-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180708_0124'),
        ('courses', '0002_auto_20180706_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Teacher', verbose_name='负责人'),
            preserve_default=False,
        ),
    ]
