# Generated by Django 2.0.6 on 2018-07-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180719_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-start_time'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='stu_num',
            field=models.IntegerField(default=0, verbose_name='报名人数'),
        ),
    ]
