# Generated by Django 2.0.6 on 2018-07-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180719_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-click_nums'], 'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
    ]
