# Generated by Django 2.0.6 on 2018-07-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCoreMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='核心成员姓名')),
                ('image', models.ImageField(upload_to='manage_site/%Y/%', verbose_name='成员照片')),
                ('postion', models.CharField(max_length=30, verbose_name='担任职位')),
                ('des', models.TextField(max_length=200, verbose_name='简单描述')),
                ('is_shown', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
        ),
        migrations.CreateModel(
            name='IndexCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程展示')),
                ('des', models.TextField(max_length=200, verbose_name='简单描述')),
                ('img', models.ImageField(max_length=30, upload_to='manage_site/%Y/%m', verbose_name='课程LOGO')),
            ],
            options={
                'verbose_name': '展示课程',
                'verbose_name_plural': '展示课程',
            },
        ),
        migrations.CreateModel(
            name='IndexHonorWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='荣誉名称')),
                ('des', models.TextField(max_length=200, verbose_name='简单描述')),
                ('is_shown', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
        ),
        migrations.CreateModel(
            name='IndexImgShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manage_site/%Y/%', verbose_name='照片')),
                ('image_name', models.CharField(default='精彩瞬间', max_length=20, verbose_name='照片名称')),
                ('des', models.TextField(max_length=200, verbose_name='照片描述')),
                ('is_shown', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '照片墙',
                'verbose_name_plural': '照片墙',
            },
        ),
    ]
