# Generated by Django 2.0.6 on 2018-07-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_site', '0003_auto_20180715_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcourse',
            name='img',
            field=models.ImageField(max_length=200, upload_to='manage_site/%Y/%m', verbose_name='课程LOGO'),
        ),
    ]
