# Generated by Django 2.0.6 on 2018-08-01 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_site', '0005_auto_20180717_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='活动名称')),
                ('des', models.TextField(max_length=200, verbose_name='简单描述')),
                ('details', models.TextField(max_length=500, verbose_name='详细信息')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '荣誉墙',
                'verbose_name_plural': '荣誉墙',
                'ordering': ['-add_time'],
            },
        ),
        migrations.DeleteModel(
            name='IndexHonorWall',
        ),
    ]
