# Generated by Django 2.0.6 on 2018-08-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_site', '0007_auto_20180801_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='details',
            field=models.TextField(default='未填', max_length=500, verbose_name='公告内容'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default='未填', max_length=100, verbose_name='标题'),
        ),
    ]
