# Generated by Django 2.0.6 on 2018-08-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_site', '0008_auto_20180801_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='首页显示'),
        ),
        migrations.AddField(
            model_name='preview',
            name='people',
            field=models.IntegerField(default=0, verbose_name='已报名人数'),
        ),
        migrations.AlterField(
            model_name='indexcoremembers',
            name='image',
            field=models.ImageField(upload_to='manage_site/member/%Y/%d', verbose_name='成员照片'),
        ),
    ]
