# Generated by Django 2.0.6 on 2018-07-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'ordering': ['-add_time'], 'verbose_name': '用户课程', 'verbose_name_plural': '用户课程'},
        ),
    ]
