# Generated by Django 2.0.6 on 2018-07-26 02:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0003_userlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.TextField(verbose_name='个人简介')),
                ('is_passed', models.BooleanField(default=False, verbose_name='审核状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '加入申请',
                'verbose_name_plural': '加入申请',
                'ordering': ['-add_time'],
            },
        ),
        migrations.DeleteModel(
            name='CourseUserAsk',
        ),
    ]
