# Generated by Django 2.0.6 on 2018-08-02 03:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_site', '0009_auto_20180802_0307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_site.Preview', verbose_name='内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'ordering': ['-add_time'],
            },
        ),
    ]
